services:
  hk-tasks-web-android:
    build: .
    container_name: hk-tasks-web-android
    restart: unless-stopped
    ports:
      - "8937:80"
    networks:
      - hk-red
networks:
  hk-red:
    external: true