// lib/core/constants/levels.dart

class NivelData {
  final int nivel;
  final String titulo;
  final String artefacto;
  final String descripcion;
  final int xpAcumulada;
  final String password;

  const NivelData({
    required this.nivel,
    required this.titulo,
    required this.artefacto,
    required this.descripcion,
    required this.xpAcumulada,
    required this.password,
  });
}

const List<NivelData> kNiveles = [
  NivelData(nivel: 1, titulo: "Iniciado de la Grieta", artefacto: "Diario de la Grieta Menor", descripcion: "Un pequeño y ajado cuaderno forrado en cuero oscuro, con bordes metálicos oxidados. En su interior, páginas de pergamino amarillento contienen garabatos frenéticos y diagramas incomprensibles.", xpAcumulada: 0, password: "Gnosis"),
  NivelData(nivel: 2, titulo: "Aprendiz de la Sizigia", artefacto: "Orbe de Alineación", descripcion: "Una esfera de cristal pesado que vibra con la energía de astros distantes. Su núcleo muestra constelaciones que cambian sutilmente cuando los opuestos se reconcilian.", xpAcumulada: 14, password: "Choripan"),
  NivelData(nivel: 3, titulo: "Escudero de Mahoraga", artefacto: "Rueda de Adaptación Fragmentada", descripcion: "Un engranaje de bronce manchado de sangre seca. Gira independientemente, otorgando a su portador una resistencia antinatural a cualquier golpe que ya haya recibido antes.", xpAcumulada: 78, password: "LCL"),
  NivelData(nivel: 4, titulo: "Rastreador de la Gnosis", artefacto: "Brújula del Pleroma", descripcion: "Instrumento de latón sin puntos cardinales. Su aguja de cuarzo ignora el norte magnético para apuntar directamente hacia la chispa divina oculta en la materia.", xpAcumulada: 215, password: "Arconte"),
  NivelData(nivel: 5, titulo: "Working Class Hero", artefacto: "Martillo del Proletariado", descripcion: "Herramienta de hierro forjado con el mango desgastado por el sudor. Al empuñarlo, la fatiga física desaparece, reemplazada por una voluntad inquebrantable de construcción.", xpAcumulada: 439, password: "Manaos"),
  NivelData(nivel: 6, titulo: "Navegante del LCL", artefacto: "Cápsula de Entry Plug", descripcion: "Tubo cilíndrico metálico que emana un constante olor a líquido amniótico y ozono. Tocarlo inunda la mente con ecos de memorias ajenas.", xpAcumulada: 762, password: "Pleroma"),
  NivelData(nivel: 7, titulo: "Hechicero de Grado Especial", artefacto: "Talismán Maldito de Rika", descripcion: "Un anillo de compromiso envuelto en vendas selladas con sangre. Susurra promesas de amor eterno que distorsionan el espacio.", xpAcumulada: 1195, password: "Lilith"),
  NivelData(nivel: 8, titulo: "Operador de Valis", artefacto: "Láser de Información Rosa", descripcion: "Un prisma cibernético que dispara haces de luz inaudibles. Su rayo descarga milenios de conocimiento filosófico directamente en la corteza cerebral.", xpAcumulada: 1746, password: "Bondi"),
  NivelData(nivel: 9, titulo: "Portador del Cristal de Plata", artefacto: "Broche de Transformación Lunar", descripcion: "Una joya resplandeciente que pulsa con la luz fría de la luna. Otorga claridad mental para purificar intenciones y desterrar la oscuridad.", xpAcumulada: 2424, password: "Demiurgo"),
  NivelData(nivel: 10, titulo: "Sintonizador de Midgar", artefacto: "Materia Verde Básica", descripcion: "Esfera translúcida de energía mako condensada. Emite un calor reconfortante y enseña los secretos más primigenios para curar heridas.", xpAcumulada: 3236, password: "Sincro"),
  NivelData(nivel: 11, titulo: "Maestro del Octavo Sentido", artefacto: "Armadura de Bronce", descripcion: "Coraza milenaria que parece viva al tacto. Se ajusta al cuerpo de quien la viste, permitiéndole moverse a velocidades que desafían la física.", xpAcumulada: 4189, password: "Quilombo"),
  NivelData(nivel: 12, titulo: "Alquimista de Amestris", artefacto: "Reloj de Bolsillo Estatal", descripcion: "Cronómetro de plata con el emblema del dragón grabado. Sus manecillas marcan el tiempo absoluto, recordando siempre el principio de intercambio equivalente.", xpAcumulada: 5291, password: "Nerv"),
  NivelData(nivel: 13, titulo: "Caminante del Rayo Rosa", artefacto: "Gafas de Philip K. Dick", descripcion: "Lentes con cristales caleidoscópicos. Al usarlos, las capas de simulación de la realidad se desprenden, revelando los patrones holográficos subyacentes.", xpAcumulada: 6548, password: "Sofia"),
  NivelData(nivel: 14, titulo: "Cazador de la Cacería Salvaje", artefacto: "Medallón de la Cacería", descripcion: "Un colgante de hueso tallado con runas nórdicas. Vibra gélidamente cuando entidades de otros mundos o depredadores nocturnos cruzan el umbral.", xpAcumulada: 7968, password: "Chamuyo"),
  NivelData(nivel: 15, titulo: "Soberano del Trono de Hierro", artefacto: "Espada de Acero Valyrio", descripcion: "Hoja oscura con aguas ondulantes en su acero. Extrañamente ligera, corta a través de la mentira y el hielo con la misma facilidad letal.", xpAcumulada: 9557, password: "Eon"),
  NivelData(nivel: 16, titulo: "Invocador de G.F. (FF8)", artefacto: "Anillo del Rey Sincorazón", descripcion: "Sortija pesada que extrae la memoria de su usuario a cambio de poder. Permite vincular la mente a entidades guardianas de poder devastador.", xpAcumulada: 11322, password: "Bersek"),
  NivelData(nivel: 17, titulo: "Pilar de la Niebla", artefacto: "Nichirin de la Niebla", descripcion: "Katana cuya hoja blanca disipa la luz. Al desenvainarla, el entorno se cubre de una bruma espesa que oculta las intenciones del portador.", xpAcumulada: 13271, password: "Coto"),
  NivelData(nivel: 18, titulo: "Arquitecto de Aperture Science", artefacto: "Pistola de Portales Básica", descripcion: "Dispositivo experimental que emite un zumbido cuántico. Altera la topología del espacio local, uniendo dos puntos distantes.", xpAcumulada: 15409, password: "Abraxas"),
  NivelData(nivel: 19, titulo: "Caballero de la Orden Assassins", artefacto: "Hoja Oculta Estándar", descripcion: "Mecanismo de muñeca preciso y letal. Requiere el sacrificio del confort pero otorga el poder de intervenir en la historia desde las sombras.", xpAcumulada: 17743, password: "Morfi"),
  NivelData(nivel: 20, titulo: "Derrumbador de Murallas (AoT)", artefacto: "Cuchillas de Equipo de Maniobras", descripcion: "Hojas de acero ultra duro, afiladas como navajas de afeitar. Diseñadas para cortar la carne de los titanes y derribar las defensas de lo inamovible.", xpAcumulada: 20281, password: "Shinji"),
  NivelData(nivel: 21, titulo: "Agente del Freeman", artefacto: "Palanca Ensangrentada", descripcion: "Barra de hierro rojo con los extremos manchados de fluidos alienígenas. Símbolo silencioso de la resistencia humana ante la opresión extradimensional.", xpAcumulada: 23028, password: "Kenoma"),
  NivelData(nivel: 22, titulo: "Portador de la Death Note", artefacto: "Fragmento de Hoja de Cuaderno Oscuro", descripcion: "Papel negro y rugoso que exuda una energía fría. Escribir un nombre en él, con el rostro en mente, asegura un final inevitable.", xpAcumulada: 25992, password: "Fernet"),
  NivelData(nivel: 23, titulo: "Maestro de la Gnosis de Arrakis", artefacto: "Anillo del Duque Leto", descripcion: "Sello ducal que huele levemente a canela y especia. Confiere la carga del liderazgo y la visión de los hilos dorados del destino en el desierto.", xpAcumulada: 29177, password: "Asuka"),
  NivelData(nivel: 24, titulo: "Viajero de la Escotilla (Lost)", artefacto: "Llave Magnética de la Iniciativa Dharma", descripcion: "Tarjeta de plástico gastado con un logo octogonal. Abre puertas hacia búnkeres olvidados y reinicia contadores que salvan o destruyen el mundo.", xpAcumulada: 32591, password: "Monada"),
  NivelData(nivel: 25, titulo: "Samurai de Tokyo Revengers", artefacto: "Chaqueta de la Tokyo Manji", descripcion: "Prenda de tela negra con kanjis dorados. Suelta un aroma a asfalto y pandillas, infundiendo un coraje kamikaze inquebrantable.", xpAcumulada: 36240, password: "Laburo"),
  NivelData(nivel: 26, titulo: "Androide de YoRHa", artefacto: "Espada Contrato Blanco", descripcion: "Arma de estética inmaculada que canta al cortar el viento. Promete una lealtad ciega y un ciclo interminable de vida, muerte y resurrección robótica.", xpAcumulada: 40129, password: "Sachiel"),
  NivelData(nivel: 27, titulo: "Brujo de la Escuela del Lobo", artefacto: "Medallón de Lobo de Plata", descripcion: "Colgante que tiembla violentamente ante la magia o monstruos. Su plata pura es un recordatorio de la delgada línea entre la humanidad y la bestia.", xpAcumulada: 44265, password: "Chispa"),
  NivelData(nivel: 28, titulo: "Guardián del Arcano (HP)", artefacto: "Varita de Saúco Quebrada", descripcion: "Fragmentos de madera oscura unidos por un hilo de luz mágica. Contiene un poder supremo pero inestable que exige maestría.", xpAcumulada: 48655, password: "Gilda"),
  NivelData(nivel: 29, titulo: "Expedicionario del Dark Side", artefacto: "Sable de Luz Carmesí Menor", descripcion: "Empuñadura metálica que proyecta una hoja de plasma rojo inestable. Crepita con ira contenida, canalizando las pasiones oscuras en poder puro.", xpAcumulada: 53305, password: "Ramiel"),
  NivelData(nivel: 30, titulo: "Jubilado del Cosmos", artefacto: "Mate Infinito del Cosmos", descripcion: "Recipiente de calabaza que contiene un universo de yerba en miniatura. Su infusión proporciona calma estelar y la perspectiva necesaria para observar el infinito.", xpAcumulada: 58221, password: "Truco"),
  NivelData(nivel: 31, titulo: "Operador de Enlace Quiral", artefacto: "Dispositivo Q-pid", descripcion: "Collar de dog tags flotantes hechas de metal quiral. Sirve para reconectar las ciudades fracturadas, tejiendo la red que desafía la extinción.", xpAcumulada: 63410, password: "Metatron"),
  NivelData(nivel: 32, titulo: "El Honorable de los Seis Ojos", artefacto: "Gafas de Sol de Satoru", descripcion: "Lentes opacos que bloquean la sobrecarga de información cuántica. Filtrar el mundo permite mantener la cordura ante la percepción absoluta del espacio.", xpAcumulada: 68878, password: "Alfajor"),
  NivelData(nivel: 33, titulo: "Arquitecto de la Gnosis", artefacto: "Pluma del Demiurgo", descripcion: "Instrumento de escritura de éter condensado. Sus trazos reescriben los dogmas físicos del universo material.", xpAcumulada: 74632, password: "Misato"),
  NivelData(nivel: 34, titulo: "Navegante del Caos", artefacto: "Caja de Lemarchand", descripcion: "Cubo rompecabezas tallado con runas doradas y lamentos. Al resolverla, desgarra el tejido de la realidad para invitar placeres y dolores más allá del entendimiento.", xpAcumulada: 80678, password: "Mate"),
  NivelData(nivel: 35, titulo: "Transmutador de Destinos", artefacto: "Círculo de Transmutación Portátil", descripcion: "Placa alquímica grabada en la piel o el metal. Facilita la deconstrucción y reconstrucción de la materia en el acto, siempre que se pague el peaje.", xpAcumulada: 87023, password: "Yaldabaoth"),
  NivelData(nivel: 36, titulo: "Consultor del I-Ching Digital", artefacto: "Monedas de Cobre Cuánticas", descripcion: "Tres monedas desgastadas que caen en múltiples estados simultáneos. Al leerlas, colapsan la probabilidad, revelando los hexagramas del cambio inminente.", xpAcumulada: 100000, password: "Otaku"),
  NivelData(nivel: 37, titulo: "Arquetipo de la Sombra (Jung)", artefacto: "Espejo del Inconsciente", descripcion: "Cristal azogado que no refleja el rostro, sino la sombra reprimida. Requiere profunda voluntad de introspección para asimilar el monstruo sin perderse.", xpAcumulada: 107314, password: "Impacto"),
  NivelData(nivel: 38, titulo: "Buda del Séptimo Vacío", artefacto: "Loto de los Siete Pétalos", descripcion: "Flor incorruptible que irradia paz absoluta. Sostenerla aquieta la mente y disuelve el ego temporal, permitiendo atisbar el vacío primordial.", xpAcumulada: 114904, password: "Gualicho"),
  NivelData(nivel: 39, titulo: "Shinobi de la Respiración Solar", artefacto: "Nichirin Solar Brillante", descripcion: "Espada que adopta el color del acero fundido. Al balancearla, emana el calor de un mediodía estival, incinerando la regeneración de las criaturas de la noche.", xpAcumulada: 122776, password: "Rei"),
  NivelData(nivel: 40, titulo: "Arquitecto de la Sincronicidad", artefacto: "Reloj de la Sincronicidad", descripcion: "Artefacto sin manecillas que vibra cuando los eventos acausales se alinean. Susurra cómo conectar los accidentes del caos para forjar un destino a medida.", xpAcumulada: 130935, password: "Subte"),
  NivelData(nivel: 41, titulo: "Piloto de la Unidad 01", artefacto: "Lanza de Longinus (Réplica)", descripcion: "Arma bífida de un rojo alienígena. Su sola presencia desestabiliza el campo de terror de las deidades, perforando directamente el alma de cualquier objetivo.", xpAcumulada: 139385, password: "Archon"),
  NivelData(nivel: 42, titulo: "Maestro de la Brújula Dorada", artefacto: "Aletiómetro de Oro", descripcion: "Medidor de la verdad cubierto de símbolos arcanos. Con la concentración adecuada, sus manecillas responden a las preguntas del inconsciente colectivo sin mentir jamás.", xpAcumulada: 148131, password: "Sacoa"),
  NivelData(nivel: 43, titulo: "Soldado de Primera Clase (FF7)", artefacto: "Espada Mortal (Buster Sword)", descripcion: "Hoja colosal y desproporcionada que guarda el peso de los legados caídos. Empuñarla exige honor, sacrificios pasados y la fuerza para cargar con los sueños de otros.", xpAcumulada: 157176, password: "Kaworu"),
  NivelData(nivel: 44, titulo: "Elegido de la Fuerza (Mando)", artefacto: "Armadura de Beskar", descripcion: "Placas de aleación indestructible que repelen proyectiles y sables de energía. El frío metal forja no solo protección, sino un credo irrompible.", xpAcumulada: 166526, password: "Rickfort"),
  NivelData(nivel: 45, titulo: "Súper Saiyajin del Caos", artefacto: "Rastreador de Ki Alterado", descripcion: "Dispositivo ocular de cristal verde que se agrieta al leer números imposibles. Permite visualizar el flujo de energía vital y anticipar el despertar del caos.", xpAcumulada: 176184, password: "Barbelo"),
  NivelData(nivel: 46, titulo: "Hechicero de la Expansión Territorial", artefacto: "Dominio Celular (Dedo de Sukuna)", descripcion: "Reliquia putrefacta e indestructible que late como un corazón envenenado. Consumirla es jugar con la muerte, ofreciendo un poder tiránico y absoluto.", xpAcumulada: 186154, password: "Salamin"),
  NivelData(nivel: 47, titulo: "Investigador de Raccoon City", artefacto: "Hierba Verde Mezclada", descripcion: "Compuesto botánico de olor intenso resguardado en un tubo de vidrio. Revitaliza células muertas y purifica toxinas en medio del apocalipsis urbano.", xpAcumulada: 196439, password: "Penpen"),
  NivelData(nivel: 48, titulo: "Velocista del Anillo de Sonic", artefacto: "Anillo Dorado de Movimiento", descripcion: "Aro flotante que emite un zumbido agudo. Al atravesarlo, el espacio se distorsiona y otorga invulnerabilidad temporal mediante hipervelocidad pura.", xpAcumulada: 207044, password: "Sefirot"),
  NivelData(nivel: 49, titulo: "Cazador de Shinigamis", artefacto: "Zanpakutō Despertada", descripcion: "Espada espiritual cuyo filo canta con la voz de su amo. Corta los lazos kármicos y libera a las almas errantes purificando la corrupción existencial.", xpAcumulada: 217972, password: "Tang"),
  NivelData(nivel: 50, titulo: "Héroe de un Solo Puñetazo", artefacto: "Guantes de Ejercicio Rotos", descripcion: "Mitones rojos desgastados por un entrenamiento obsesivo. Rompieron el limitador biológico; con ellos, un solo impacto detiene cualquier fuerza del universo.", xpAcumulada: 229227, password: "Bolonqui"),
  NivelData(nivel: 51, titulo: "Mago del Ministerio del Caos", artefacto: "Vara del Caos", descripcion: "Báculo de madera retorcida, vivo y rebelde. No conjura hechizos estructurados, sino que canaliza la improbabilidad cuántica de los sigilos más salvajes.", xpAcumulada: 240811, password: "Merluza"),
  NivelData(nivel: 52, titulo: "Usuario de la Piedra Filosofal", artefacto: "Fragmento de Piedra Filosofal", descripcion: "Cristal rojo líquido de densidad incalculable. Sangra energía de almas atrapadas y evade las leyes de la termodinámica para conceder poder divino temporal.", xpAcumulada: 252729, password: "Birra"),
  NivelData(nivel: 53, titulo: "Observador de la Realidad Ubik", artefacto: "Aerosol Ubik", descripcion: "Lata oxidada con una válvula obstruida. Su rocío revierte la descomposición del espacio-tiempo, anclando al usuario a la realidad objetiva cuando el mundo se licúa.", xpAcumulada: 264984, password: "Leliel"),
  NivelData(nivel: 54, titulo: "Inquisidor de Novigrad", artefacto: "Medallón de Fuego de Igni", descripcion: "Insignia mágica ardiente al tacto. Canaliza la furia interna en tormentas de fuego líquido, reduciendo armaduras pesadas a escoria humeante.", xpAcumulada: 277579, password: "Fachero"),
  NivelData(nivel: 55, titulo: "Arquitecto del Laberinto de Alan Wake", artefacto: "Página del Manuscrito Modificada", descripcion: "Hoja escrita a máquina donde la ficción reescribe la materia. Lo que se redacta en ella altera el entorno, transformando sombras en enemigos o aliados.", xpAcumulada: 290518, password: "Zeruel"),
  NivelData(nivel: 56, titulo: "Viajero del Agujero de Gusano", artefacto: "Cristal de Agujero de Gusano", descripcion: "Gema prismática que condensa la inmensidad del éter. Romperla abre un puente de Einstein-Rosen instantáneo hacia cualquier coordenada mental previamente visitada.", xpAcumulada: 303803, password: "Mandanga"),
  NivelData(nivel: 57, titulo: "Mutante del Nivel Omega (Marvel)", artefacto: "Gen X Mutado", descripcion: "Secuencia de ADN cristalizada en una ampolleta. Despierta un dominio sobre las fuerzas fundamentales, redefiniendo los límites de la evolución biológica humana.", xpAcumulada: 317438, password: "Carpincho"),
  NivelData(nivel: 58, titulo: "Protector de Gotham", artefacto: "Batarang de Carbono", descripcion: "Proyectil táctico afilado como una cuchilla, forjado en la oscuridad. Símbolo del triunfo del ingenio, la preparación y la psicología sobre el miedo mismo.", xpAcumulada: 331427, password: "Israfel"),
  NivelData(nivel: 59, titulo: "Maestro del Wonderboy", artefacto: "Gorra de Wonderboy", descripcion: "Prenda clásica y resistente que confiere una agilidad pixelada. Otorga al usuario la pericia para sortear trampas mortales con reflejos imposibles.", xpAcumulada: 345772, password: "Atorrante"),
  NivelData(nivel: 60, titulo: "Psíquico del Porcentaje 100", artefacto: "Cuchara Doblada por la Mente", descripcion: "Cubierto de plata deformado permanentemente por voluntad pura. Sirve como catalizador para descargar presiones psíquicas masivas al borde de la explosión emocional.", xpAcumulada: 360476, password: "Sandalphon"),
  NivelData(nivel: 61, titulo: "Líder de la Toman", artefacto: "Bandera de la Primera Generación", descripcion: "Estandarte pesado de tela oscura. Portarlo aglutina la fuerza de mil marginados, volviendo la voluntad colectiva del grupo una entidad inquebrantable.", xpAcumulada: 375543, password: "Mistica"),
  NivelData(nivel: 62, titulo: "Alquimista de la Puerta de la Verdad", artefacto: "La Puerta de la Verdad en Miniatura", descripcion: "Relieve de piedra adornado con el árbol de la vida. A través de él asoma el Ojo que todo lo ve, cobrando un alto peaje por conocimiento infinito.", xpAcumulada: 390975, password: "Gato"),
  NivelData(nivel: 63, titulo: "Operador de la Cuchilla Oculta", artefacto: "Guantelete del Asesino Maestro", descripcion: "Brazalete ornamentado con filos gemelos y ganchos tácticos. Representa la cumbre de una estirpe letal, garantizando la caída de tiranos en pleno silencio.", xpAcumulada: 406775, password: "Matriz"),
  NivelData(nivel: 64, titulo: "Dragón de Namek", artefacto: "Esfera del Dragón de 4 Estrellas", descripcion: "Globo ambarino que pulsa suavemente y contiene cuatro astros inmutables. Es la llave para convocar a entidades cósmicas y torcer las leyes de la muerte.", xpAcumulada: 422946, password: "Monono"),
  NivelData(nivel: 65, titulo: "Maestro del Kaio-Ken", artefacto: "Aura Roja del Kaio-Ken", descripcion: "Fragmento de energía carmesí solidificada. Multiplica el rendimiento físico exponencialmente a expensas de desgarrar los músculos de quien no tenga disciplina marcial plena.", xpAcumulada: 439492, password: "Bardero"),
  NivelData(nivel: 66, titulo: "Sexto Ojo del Infinito", artefacto: "Venda de los Seis Ojos", descripcion: "Banda de tela impregnada de hechicería. Cubrirse con ella paradójicamente expande la percepción hasta el límite subatómico, otorgando supremacía en cualquier duelo.", xpAcumulada: 456414, password: "Sophia"),
  NivelData(nivel: 67, titulo: "Portador de Excalibur", artefacto: "Vaina de Avalon", descripcion: "Estuche de espada dorado y luminoso. Su portador es incapaz de sangrar; las heridas mortales se curan instantáneamente bajo su halo de realeza mítica.", xpAcumulada: 473715, password: "Fulbo"),
  NivelData(nivel: 68, titulo: "Cazador de Demonios de Clase S", artefacto: "Espada Kurikara", descripcion: "Katana ancestral rodeada en llamas azules inextinguibles. Libera por completo el linaje demoníaco oculto de su usuario, transformando el odio en poder salvador.", xpAcumulada: 491398, password: "Bardiel"),
  NivelData(nivel: 69, titulo: "Maestro de la Brújula de Dick", artefacto: "Radio Interdimensional de Dick", descripcion: "Transmisor rudimentario ensamblado con chatarra. Sintoniza frecuencias de líneas temporales adyacentes, trayendo voces que advierten sobre futuros colapsos.", xpAcumulada: 509466, password: "Guita"),
  NivelData(nivel: 70, titulo: "Elegido de la Sizigia Solar", artefacto: "Disco Solar de la Sizigia", descripcion: "Placa de oro caliente que proyecta un eclipse perpetuo. Anula la división entre luz y oscuridad, uniendo la mente analítica con la intuición mística.", xpAcumulada: 527920, password: "Sahaquiel"),
  NivelData(nivel: 71, titulo: "Comandante del Reconocimiento", artefacto: "Capa de la Legión de Reconocimiento", descripcion: "Manto verde desgastado y con olor a libertad y sangre titanica. Las Alas de la Libertad bordadas en la espalda otorgan inmunidad al terror paralizante.", xpAcumulada: 546765, password: "Armisael"),
  NivelData(nivel: 72, titulo: "Archivista del Pleroma", artefacto: "Códice de Nag Hammadi", descripcion: "Papiro antiguo indestructible escrito en copto brillante. Leerlo otorga revelaciones directas sobre la naturaleza ilusoria del mundo, desmantelando archones mentales.", xpAcumulada: 565995, password: "Tabris"),
  NivelData(nivel: 73, titulo: "Maestro de la Magia de Sigilos", artefacto: "Tiza de Sigilos Infinitos", descripcion: "Pedazo de yeso lunar que jamás se consume. Traza geometrías que burlan la censura del ego, materializando deseos directamente en el inconsciente colectivo.", xpAcumulada: 585614, password: "Peronismo"),
  NivelData(nivel: 74, titulo: "Guardián de la Heladera de Acero", artefacto: "Llave de la Heladera de Acero", descripcion: "Llave fría al tacto que abre compartimentos interdimensionales. Garantiza la conservación de los recursos más vitales ante el cataclismo entrópico.", xpAcumulada: 605625, password: "Entropia"),
  NivelData(nivel: 75, titulo: "Héroe del LCL Rojo", artefacto: "Mar de LCL Concentrado", descripcion: "Frasco que contiene el caldo primordial. Bebiendo de él, las fronteras del ego se diluyen, compartiendo el entendimiento compasivo de todos los seres caídos.", xpAcumulada: 626029, password: "Chorizo"),
  NivelData(nivel: 76, titulo: "Viajero de la Playa (DS2)", artefacto: "Reloj de Bolsillo de Fragile", descripcion: "Aparato que no mide el tiempo local, sino la degradación quiral. Advierte la llegada de las lluvias del tiempo que aceleran la vejez y la putrefacción celular.", xpAcumulada: 646830, password: "Anunnaki"),
  NivelData(nivel: 77, titulo: "Operador del Odradek Dorado", artefacto: "Odradek de Oro Macizo", descripcion: "Escáner robótico con forma de flor mecánica. Se acopla al hombro y parpadea con luz cegadora al detectar anomalías espectrales que perturban el tejido espacial.", xpAcumulada: 668028, password: "Diego"),
  NivelData(nivel: 78, titulo: "Maestro de la Quintaesencia", artefacto: "Cristal de Quintaesencia Pura", descripcion: "Prisma etéreo, el quinto elemento condensado. Sostenerlo equilibra perfectamente los humores del cuerpo y proyecta voluntad pura sobre los elementos terrenales.", xpAcumulada: 689626, password: "Mesias"),
  NivelData(nivel: 79, titulo: "Guerrero de la Armadura Divina", artefacto: "Armadura Escama Divina", descripcion: "Coraza que refulge con el brillo de un dios despertado. Otorga invulnerabilidad absoluta y alas de pura energía astral para cruzar galaxias enteras de un salto.", xpAcumulada: 711627, password: "Patagon"),
  NivelData(nivel: 80, titulo: "Sumo Sacerdote de Hello Kitty", artefacto: "Peluche Dimensional de Hello Kitty", descripcion: "Muñeco sin boca, de ternura inquietante. Quien lo abraza es trasladado a un espacio liminal donde los horrores de la adultez son filtrados en pura compasión pop.", xpAcumulada: 734033, password: "Gauchito"),
  NivelData(nivel: 81, titulo: "Maestro del Arte de Perder el Control", artefacto: "Brazalete del Club de la Pelea", descripcion: "Tira de cuero manchada y sudorosa. Aceptarla significa tocar fondo voluntariamente, hallando libertad nihilista en la destrucción de las ataduras consumistas.", xpAcumulada: 756845, password: "Obelisco"),
  NivelData(nivel: 82, titulo: "Sintonizador de la Radio de Silent Hill", artefacto: "Radio Estática de Niebla", descripcion: "Dispositivo analógico que emite ruido blanco ensordecedor. Se vuelve más histérica a medida que los monstruos nacidos del trauma profundo se acercan en la bruma.", xpAcumulada: 780066, password: "Destino"),
  NivelData(nivel: 83, titulo: "Hacker del Kernel de Matrix", artefacto: "Disco Flexible de Zion", descripcion: "Disquete reliquia de los albores de la red. Contiene un script root capaz de manipular los cimientos numéricos de la ilusión simulada a voluntad.", xpAcumulada: 803698, password: "Victoria"),
  NivelData(nivel: 84, titulo: "Viajero de los 108 Caminos", artefacto: "Pergamino de los 108 Destinos", descripcion: "Rollo de seda interminable que cartografía las reencarnaciones pasadas. Permite asimilar lecciones y técnicas marciales de vidas olvidadas.", xpAcumulada: 827743, password: "Astral"),
  NivelData(nivel: 85, titulo: "Maestro del I-Ching Cuántico", artefacto: "Monedas de I-Ching Holográficas", descripcion: "Discos digitales que giran suspendidos en el aire. Sus resultados probabilísticos dictan acciones con una tasa de éxito matemático absolutamente perfecto.", xpAcumulada: 852202, password: "Gil"),
  NivelData(nivel: 86, titulo: "Cazador de la Luz Despertada", artefacto: "Orbe de Luz Despertada", descripcion: "Núcleo lumínico de un santuario antiguo. Ciega a los corruptos y baña a su portador con la certeza estoica necesaria para enfrentar batallas ya perdidas.", xpAcumulada: 877078, password: "Conurbano"),
  NivelData(nivel: 87, titulo: "Operador de la Máquina de Alan Wake", artefacto: "Máquina de Escribir Antigüa", descripcion: "Artefacto de teclas pesadas y sonoras. Cada letra golpeada sobre el papel se codifica como ley física en la realidad, armando el andamiaje del mundo.", xpAcumulada: 902373, password: "Cuarteto"),
  NivelData(nivel: 88, titulo: "Soberano de la Gnosis Eterna", artefacto: "Corona del Pleroma", descripcion: "Diadema de luz inmaterial invisible para los ciegos espirituales. Consagra a su portador como un arquitecto de la chispa divina, libre del yugo del creador inferior.", xpAcumulada: 928088, password: "Milanesa"),
  NivelData(nivel: 89, titulo: "Maestro de la Sizigia Infinita", artefacto: "Prisma de la Sizigia", descripcion: "Poliedro cristalino perfecto que fracciona la realidad en dualidades armoniosas. Fusiona cuerpo y sombra, otorgando la completitud psicológica absoluta.", xpAcumulada: 954225, password: "Logos"),
  NivelData(nivel: 90, titulo: "Héroe de la Clase Obrera Galáctica", artefacto: "Hoz y Martillo Estelares", descripcion: "Armas celestiales forjadas en el núcleo de estrellas muertas. Representan la emancipación de todo ser vivo a nivel cósmico, aplastando tiranías siderales.", xpAcumulada: 980786, password: "Monolito"),
  NivelData(nivel: 91, titulo: "Guardián del Umbral de Dick", artefacto: "Ojo Omnisciente de VALIS", descripcion: "Satélite alienígena en miniatura de color rosa intenso. Transmite telepatía satelital continua, descodificando la red de inteligencia universal.", xpAcumulada: 1007773, password: "Reclamo"),
  NivelData(nivel: 92, titulo: "Alquimista del Sol de Amestris", artefacto: "Sol Embotellado de Xerxes", descripcion: "Esfera de cristal hermética que contiene una pequeña estrella moribunda. Ofrece poder calórico ilimitado y los oscuros susurros de naciones enteras sacrificadas.", xpAcumulada: 1035188, password: "Burocracia"),
  NivelData(nivel: 93, titulo: "Maestro del Vacío de Krishnamurti", artefacto: "Campana del Vacío de Jiddu", descripcion: "Instrumento de cobre liso sin badajo. Su sonido sólo reverbera en la mente sin condicionamientos, aniquilando al observador para fundirlo con lo observado.", xpAcumulada: 1063032, password: "Afip"),
  NivelData(nivel: 94, titulo: "Operador del Sistema de Destino", artefacto: "Matriz del Destino Programable", descripcion: "Tablero fractal con terminales nerviosas. Quien lo domina puede tipear directamente sobre el hilo de las Parcas, alterando desenlaces mortales.", xpAcumulada: 1091307, password: "Vacio"),
  NivelData(nivel: 95, titulo: "Elegido del Rayo Rosa Supremo", artefacto: "Proyector de Rayo Rosa", descripcion: "Artefacto biomecánico que emite luz de alta frecuencia informativa. Dispara ráfagas de epifanías instantáneas que reescriben los paradigmas existenciales.", xpAcumulada: 1119998, password: "Despertar"),
  NivelData(nivel: 96, titulo: "Arquitecto de la Nueva Arrakis", artefacto: "Gusano de Arena Cristalizado", descripcion: "Espécimen petrificado gigantesco. Controlarlo permite cabalgar sobre los cimientos mismos de los planetas y doblegar la especia que mueve el universo.", xpAcumulada: 1149129, password: "Albedrio"),
  NivelData(nivel: 97, titulo: "Señor del Tiempo de la Grieta", artefacto: "Cronómetro de la Grieta", descripcion: "Reloj de bolsillo donde las agujas avanzan, retroceden o desaparecen. Domina los pliegues temporales cerrados y permite observar la fisura del inicio de todo.", xpAcumulada: 1178696, password: "Karma"),
  NivelData(nivel: 98, titulo: "Maestro de la Ilusión de la Verdad", artefacto: "Espejo de las Mil Verdades", descripcion: "Superficie pulida que refleja todas las versiones posibles de un individuo. El maestro verdadero elige qué reflejo manifestar para reescribir su propia historia.", xpAcumulada: 1208702, password: "Chorro"),
  NivelData(nivel: 99, titulo: "Portador de la Realidad Permeable", artefacto: "Controlador de la Realidad", descripcion: "Un joystick monolítico y arcano sin botones. Sus comandos operan a través del pensamiento puro, operando sobre las mismísimas leyes de la física y el azar.", xpAcumulada: 1239148, password: "Apocalipsis"),
  NivelData(nivel: 100, titulo: "Avatar de la Gnosis de Todo", artefacto: "Aleph del Todo", descripcion: "Una pequeña esfera iridiscente de apenas centímetros. Al mirarla con detención, se pueden ver simultáneamente todos los puntos, instantes y misterios del universo entero.", xpAcumulada: 1359049, password: "Instrumentalidad"),
];

int calcularNivel(int xpTotal) {
  for (int i = kNiveles.length - 1; i >= 0; i--) {
    if (xpTotal >= kNiveles[i].xpAcumulada) return kNiveles[i].nivel;
  }
  return 1;
}

double calcularProgreso(int xpTotal, int nivelActual) {
  if (nivelActual >= 100) return 1.0;
  final xpActual = kNiveles[nivelActual - 1].xpAcumulada;
  final xpSiguiente = kNiveles[nivelActual].xpAcumulada;
  return ((xpTotal - xpActual) / (xpSiguiente - xpActual)).clamp(0.0, 1.0);
}

NivelData getNivelData(int nivel) {
  return kNiveles[(nivel - 1).clamp(0, 99)];
}

const int XP_POR_MISION = 777;
